### ISSUE TITLE
Define configuration file format

### ISSUE THREAD

**Issue by Michionlion** [GatorEducator/gatorgradle#1]
We need to define a file format for the configuration file. It should allow tree-like editing, so that something like the below is possible:

```
gatorgrader:
  directory:
    writing:
      file:
        reflection.md:
          paragraphs: 4
          sentences: 3
    src/java/main/samplelab:
      file:
        SampleLabMain.java:
          fragment:
            "println(": 2
              "new Date": 1
mdl:
  file:
    writing/reflection.md
    README.md
```

This example is quite verbose, so we should attempt to find alternatives that allow for the same specificity and flexibility without the extra lines and nesting. Our goal should be to minimize length and complexity, and maximize comprehensibility and flexibility. Possible options include better file specification syntax, or rethinking the nesting structure.
